---
title: "sampling_frequency"
format: html
editor: source
---

```{r, message=FALSE}
library(tidyverse)

source("../../R/load_functions.R")
triggerR <- load_trigger_functions()
rm(load_trigger_functions)
dir.create("../../outputs/sampling_frequency", showWarnings = F)
```

```{r}
accounts <- if (!exists("accounts")) {
  triggerR$active_accounts()
} else accounts

trigger_daily <- if (!exists("trigger_daily")) {
  triggerR$read_trigger_tables(granularity = "daily", cores = 5)
} else trigger_daily
```


## GPS, SMH, SML, AIR

```{r, fig.width=12, fig.height=12}
p_occ <- trigger_daily %>%
  select(source, userId, date, n_records_total) %>%
  distinct() %>%
  filter(!is.na(userId), source != "sleep") %>%
  filter(date >= as.Date("2025-03-01"),
         date <= Sys.Date()) %>%
  #filter(date >= as.Date("2025-03-01")) %>%
  left_join(accounts, "userId") %>%
  arrange(country, userId, date) %>%
  mutate(userId = factor(userId, levels = unique(userId))) %>%
  mutate(country_x = min(date) -1) %>%
  ggplot(aes(x = date, y = userId, fill = n_records_total)) +
  geom_tile() +
  theme_minimal(base_size = 24) +
  scale_fill_viridis_c(option = "H", trans = "log10",
                       label = scales::label_scientific(),
                       name   = "n (log10)") +
  theme(legend.position = "bottom",
        axis.text.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.text = element_text(size = 12, angle = 45, hjust = 1, vjust = 1)) +
  ggnewscale::new_scale_fill() +
  geom_tile(
    aes(x = country_x, fill = country),
    width = 10,
    show.legend = TRUE
  ) +
  scale_x_date(expand = expansion(mult = c(0, 0))) +
  facet_wrap(~source) +
  theme(
    panel.grid.major.y = element_line(linewidth = 0.2),
    panel.grid.minor.y = element_line(linewidth = 0.2))
p_occ
```

```{r}
png(filename = "../../outputs/sampling_frequency/HF_sampling_freq_user_heatmap.png",
    width = 12*300, height = 12*300, res = 300)
p_occ
dev.off()
```


## SLEEP

```{r, fig.width=6, fig.height=6}
p_occ <- trigger_daily %>%
  filter(!is.na(userId), source == "sleep") %>%
  select(source, userId, date) %>%
  distinct() %>%
  filter(date >= as.Date("2025-03-01"),
         date <= Sys.Date()) %>%
  mutate(recorded = "Recorded") %>%
  left_join(accounts, "userId") %>%
  arrange(country, userId, date) %>%
  mutate(userId = factor(userId, levels = unique(userId))) %>%
  mutate(country_x = min(date) - 1) %>%
  ggplot(aes(x = date, y = userId, fill = recorded)) +
  geom_tile() +
  scale_fill_manual(values = c(Recorded = "#F8766D"), guide = "none") +
  theme_minimal(base_size = 24) +
  theme(
    legend.position = "bottom",
    axis.text.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  ) +
  ggnewscale::new_scale_fill() +
  geom_tile(
    aes(x = country_x, fill = country),
    width = 10,
    show.legend = TRUE
  ) +
  scale_x_date(expand = expansion(mult = c(0, 0))) +
  theme(
    panel.grid.major.y = element_line(linewidth = 0.2),
    panel.grid.minor.y = element_line(linewidth = 0.2)
  )

p_occ
```

```{r}
png(filename = "../../outputs/sampling_frequency/DLY_SLP_sampling_freq_user_heatmap.png",
    width = 12*300, height = 12*300, res = 300)
p_occ
dev.off()
```

```{r}
rm(p_occ)
```















