---
title: "environmental_indicators"
format: html
editor: source
---

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
```

## V1

```{r}
tbl_heat <- list.files("../raw/v1/", full.names = TRUE) %>%
  map(function(path) {
    city <- basename(path) %>%
      stringr::str_remove("^heatwave_") %>%
      stringr::str_remove("_2025_with_t2m_utci\\.csv$")

    txt <- readr::read_file(path) %>%
      stringr::str_replace_all("\r\r\n", "\n") %>%
      stringr::str_replace_all("\r\n", "\n") %>%
      stringr::str_replace_all("\r", "\n")

    read_csv(
      I(txt),
      col_types = cols(
        date = col_character(),
        utci_daily_mean = col_double(),
        t2m_daily_mean = col_double(),
        posEHF = col_character(),
        Euroheat = col_character()
      ),
      skip_empty_rows = TRUE
    ) %>%
      filter(!is.na(date), date != "") %>%
      mutate(
        city = stringr::str_to_title(city),
        date = lubridate::as_date(date),
        posEHF = posEHF == "True",
        Euroheat = Euroheat == "True",
        .before = 1
      )
  }) %>%
  bind_rows()
```

```{r}
any(tbl_heat$posEHF & tbl_heat$Euroheat)
```


```{r}
tbl_heat <- tbl_heat %>%
  mutate(heatwave_type = case_when(posEHF & Euroheat ~ "both",
                                   posEHF & !Euroheat ~ "ehf_only",
                                   !posEHF & Euroheat ~ "euroheat_only",
                                   TRUE ~ "no_event"),
         heatwave_type = factor(heatwave_type,
                                levels = c("both", "ehf_only",
                                           "euroheat_only", "no_event")))
```

```{r}
write_csv(tbl_heat, "../processed/thermal_daily_2025_v1.csv")
```


## V2

```{r}
tbl_heat <- list.files("../raw/v2", full.names = TRUE) %>%
  map(\(path){
    
    city <- str_remove(basename(path), "_UTCI_timeseries\\.csv$")
    read_csv(path, show_col_types = F) %>%
      mutate(city = city, .before = 1) %>%
      mutate(date = as_date(valid_time),
             hour = hour(valid_time),
             .after = city)
  }) %>%
  bind_rows() %>%
  mutate(
    utci_c = utci - 273.15,
    utci_stress_class = case_when(
      utci_c > 46 ~ "Extreme heat stress",
      utci_c > 38 & utci_c <= 46 ~ "Very strong heat stress",
      utci_c > 32 & utci_c <= 38 ~ "Strong heat stress",
      utci_c > 26 & utci_c <= 32 ~ "Moderate heat stress",
      utci_c > 9 & utci_c <= 26 ~ "No thermal stress",
      utci_c > 0 & utci_c <= 9 ~ "Slight cold stress",
      utci_c > -13 & utci_c <= 0 ~ "Moderate cold stress",
      utci_c > -27 & utci_c <= -13 ~ "Strong cold stress",
      utci_c > -40 & utci_c <= -27 ~ "Very strong cold stress",
      utci_c <= -40 ~ "Extreme cold stress",
      TRUE ~ NA_character_),
    
    utci_stress_class = factor(
      utci_stress_class,
      levels = c(
        "Extreme cold stress",
        "Very strong cold stress",
        "Strong cold stress",
        "Moderate cold stress",
        "Slight cold stress",
        "No thermal stress",
        "Moderate heat stress",
        "Strong heat stress",
        "Very strong heat stress",
        "Extreme heat stress"
      )))
```

```{r}
write_csv(tbl_heat, "../processed/thermal_hourly_v2.csv")
```









