---
title: "correlation_analysis"
format: html
editor: source
---

```{r, message=FALSE}
library(tidyverse)
library(ggnewscale)

source(here::here("scripts", "load_functions.R"))
triggerR <- load_trigger_functions()
```

```{r}
accounts <- if (!exists("accounts")) {
  triggerR$active_accounts()
} else accounts

trigger_daily <- if (!exists("trigger_daily")) {
  triggerR$read_trigger_tables(granularity = "daily", cores = 5, min_obs_per_hour = 10)
} else trigger_daily

trigger_hourly <- if (!exists("trigger_hourly")) {
  triggerR$read_trigger_tables(granularity = "hourly", cores = 5)
} else trigger_hourly
```

## Hourly

```{r}
mat_hourly <- trigger_hourly %>%
  filter(!is.na(userId), type %in% c("sum", "mean"), !is.na(value)) %>%
  filter(date >= as.Date("2025-03-01"), date <= Sys.Date()) %>%
  select(userId, date, hour, measurement, value) %>%
  unite("sample", userId, date, hour) %>%
  group_by(sample, measurement) %>%
  mutate(n = n()) %>%
  filter(n==1) %>%
  select(-n) %>%
  pivot_wider(names_from = "measurement", values_from = "value", values_fill = NA_real_) %>%
  column_to_rownames("sample")
```

```{r}
# =========================
# 1. MATRICE CORRELAZIONE
# =========================
cor_hourly <- cor(mat_hourly, use = "pairwise.complete.obs", method = "spearman")

# =========================
# 2. MATRICE n_pair
# =========================
pairs_hourly <- outer(
  colnames(mat_hourly),
  colnames(mat_hourly),
  Vectorize(function(x, y) {
    sum(complete.cases(mat_hourly[, c(x, y)]))
  })
)

rownames(pairs_hourly) <- colnames(pairs_hourly) <- colnames(mat_hourly)

# =========================
# 3. LONG FORMAT
# =========================
cor_df <- cor_hourly %>%
  as_tibble(rownames = "Var1") %>%
  pivot_longer(-Var1, names_to = "Var2", values_to = "cor")

pairs_df <- pairs_hourly %>%
  as_tibble(rownames = "Var1") %>%
  pivot_longer(-Var1, names_to = "Var2", values_to = "n_pair")

var_names <- colnames(mat_hourly)
plot_df <- left_join(cor_df, pairs_df, by = c("Var1", "Var2")) %>%
  mutate(
    i = match(Var1, var_names),
    j = match(Var2, var_names),
    triangle = case_when(
      i < j ~ "upper",
      i > j ~ "lower",
      TRUE ~ "diag"
    ),
    Var1 = factor(Var1, levels = var_names),
    Var2 = factor(Var2, levels = var_names)
  ) %>%
  complete(Var1, Var2)

rm(cor_df, pairs_df)
```


```{r, fig.width=9, fig.height=8, warning=FALSE}
# =========================
# 4. PLOT
# =========================
p_hourly <- ggplot() +
    geom_tile(
    data = plot_df,
    aes(x = Var1, y = Var2),
    fill = "white",
    color = "grey"
  ) +
  geom_tile(
    data = filter(plot_df, triangle == "upper"),
    aes(x = Var1, y = Var2, fill = cor), color = "grey") +
  scale_fill_gradient2(
    low = "#3B4CC0", mid = "white", high = "#B40426",
    midpoint = 0, limits = c(-1, 1), name = "Correlation",
    na.value = "black") +
  ggnewscale::new_scale_fill() +
  geom_tile(
    data = filter(plot_df, triangle == "lower"),
    aes(x = Var1, y = Var2, fill = n_pair), 
    color = "grey") +
  scale_fill_viridis_c(
    option = "D", name = "N pairs", trans = "log10", na.value = "black") +
  coord_fixed() +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_blank())

p_hourly
```

```{r}
ggsave(
  filename = here::here("outputs", "correlation_hourly.png"),
  plot = p_hourly,
  width = 9,
  height = 8,
  dpi = 300
)
```

### Daily

```{r}
mat_daily <- trigger_daily %>%
  filter(!is.na(userId), type %in% c("sum", "mean", "daily"),
         !is.na(value)) %>%
  filter(date >= as.Date("2025-03-01"), date <= Sys.Date()) %>%
  filter(n_hours_covered >= 10 | source == "sleep") %>%
  select(userId, date, measurement, value) %>%
  unite("sample", userId, date) %>%
  pivot_wider(names_from = "measurement", values_from = "value", values_fill = NA_real_) %>%
  column_to_rownames("sample")
```

```{r, warning=FALSE}
# =========================
# 1. MATRICE CORRELAZIONE
# =========================
cor_daily <- cor(mat_daily, use = "pairwise.complete.obs", method = "spearman")

# =========================
# 2. MATRICE n_pair
# =========================
pairs_daily <- outer(
  colnames(mat_daily),
  colnames(mat_daily),
  Vectorize(function(x, y) {
    sum(complete.cases(mat_daily[, c(x, y)]))
  })
)

rownames(pairs_daily) <- colnames(pairs_daily) <- colnames(mat_daily)

# =========================
# 3. LONG FORMAT
# =========================
cor_df <- cor_daily %>%
  as_tibble(rownames = "Var1") %>%
  pivot_longer(-Var1, names_to = "Var2", values_to = "cor")

n_df <- pairs_daily %>%
  as_tibble(rownames = "Var1") %>%
  pivot_longer(-Var1, names_to = "Var2", values_to = "n_pair")

var_names <- colnames(mat_daily)
plot_df <- left_join(cor_df, n_df, by = c("Var1", "Var2")) %>%
  mutate(
    i = match(Var1, var_names),
    j = match(Var2, var_names),
    triangle = case_when(
      i < j ~ "upper",
      i > j ~ "lower",
      TRUE ~ "diag"
    ),
    Var1 = factor(Var1, levels = var_names),
    Var2 = factor(Var2, levels = var_names)
  )
```


```{r, fig.width=9, fig.height=8}
# =========================
# 4. PLOT
# =========================
p_daily <- ggplot() +
    geom_tile(
    data = plot_df,
    aes(x = Var1, y = Var2),
    fill = "white",
    color = "grey80"
  ) +
  geom_tile(
    data = filter(plot_df, triangle == "upper"),
    aes(x = Var1, y = Var2, fill = cor), color = "grey80") +
  scale_fill_gradient2(
    low = "#3B4CC0", mid = "white", high = "#B40426",
    midpoint = 0, limits = c(-1, 1), name = "Correlation",
    na.value = "black") +
  ggnewscale::new_scale_fill() +
  geom_tile(
    data = filter(plot_df, triangle == "lower"),
    aes(x = Var1, y = Var2, fill = n_pair), 
    color = "grey80") +
  scale_fill_viridis_c(
    option = "D", name = "N pairs", trans = "log10", na.value = "black") +
  coord_fixed() +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_blank())

p_daily
```

```{r}
ggsave(
  filename = here::here("outputs", "correlation_daily.png"),
  plot = p_daily,
  width = 9,
  height = 8,
  dpi = 300
)
```


```{r}
rm(cor_daily, cor_hourly, cor_df, mat_daily, mat_hourly, n_df, n_mat, pairs_df,
   pairs_daily, pairs_hourly, p_daily, p_hourly, var_names, plot_df, cor_mat)
```

