---
title: "age_sex"
format: html
editor: source
---

```{r, message=FALSE}
library(tidyverse)
library(readxl)

source("../../../R/load_functions.R")
triggerR <- load_trigger_functions("../../../R/")
rm(load_trigger_functions)
dir.create("../../outputs/cumulative_records", showWarnings = F)
```

```{r}
accounts <- triggerR$active_accounts()
```

```{r, message=FALSE}
info_CH <- read_csv("../raw/genre age participants_CH.csv") %>%
  rename(id = `User ID App`, sex = Genre, age = Age) %>%
  mutate(age_group = cut(age, breaks = seq(0, 100, by = 10),
                         right = FALSE, labels = 0:9, ordered_result = TRUE),
         sex = as_factor(sex)) %>%
  mutate(email = str_sub(id, 1, 8)) %>%
  select(email, sex, age, age_group)

info_DE <- read_csv("../raw/prelim_data_longcl_augsburg.csv") %>%
  rename(sex = `sex/gender`, age = `age at inclusion`) %>%
  mutate(sex = str_to_upper(sex), sex = as_factor(sex)) %>%
  mutate(age_group = cut(age, breaks = seq(0, 100, by = 10),
                         right = FALSE, labels = 0:9, ordered_result = TRUE)) %>%
  mutate(email = str_sub(id, 1, 8)) %>%
  select(email, sex, age, age_group)

info_IT <- read_csv("../raw/tab_ID_GEN_AGE_UOULU.csv") %>%
  rename(sex = gender, age_group = age_cat, id = ID) %>%
  mutate(email = str_sub(id, 1, 8)) %>%
  mutate(age_group = factor(age_group, levels = 0:9, ordered = T),
         sex = if_else(sex == 1, "M", "F")) %>%
  select(email, sex, age_group)

info <- bind_rows(info_IT, info_DE, info_CH)
write_tsv(info, "../processed/info_age_sex.tsv")
```

```{r}
accounts <- accounts %>%
  left_join(info, by = "email")

write_tsv(accounts, "../processed/accounts_info_age_sex.tsv")
```














