---
title: "prepare_heatwave_tpot2_dataset"
format: html
editor: source
---

```{r, message=FALSE}
library(tidyverse)

source("../../../R/load_functions.R")
triggerR <- load_trigger_functions("../../../R")
rm(load_trigger_functions)
```

```{r}
accounts <- if (!exists("accounts")) {
  triggerR$active_accounts()
} else accounts

trigger_daily <- if (!exists("trigger_daily")) {
  triggerR$read_trigger_tables(granularity = "daily", cores = 5, min_obs_per_hour = 10)
} else trigger_daily

trigger_sleep <- if (!exists("trigger_sleep")) {
  triggerR$sleep_tidy()
} else trigger_sleep

trigger_daily_with_sleep <- bind_rows(trigger_daily, trigger_sleep)
```

```{r}
heatwave <- read_csv("../../../data/environmental_indicators/processed/thermal_daily_2025.csv",
                     show_col_types = F) %>%
  mutate(heatwave = posEHF | Euroheat) %>%
  select(city, date, heatwave) %>%
  mutate(country = case_when(
    city == "Augsburg" ~ "DE",
    city == "Bologna" ~ "IT",
    city == "Geneve" ~ "CH",
    city == "Heraklion" ~ "GR")) %>%
  mutate(heatwave = as.numeric(heatwave)) 
```

## ALL

```{r, fig.width=12, fig.height=12}
df <- trigger_daily_with_sleep %>%
  filter(source != "gps", !is.na(value),
         !(userId == 61 & date == as.Date("2025-07-30")),
         #n_hours_covered >= 16,
         source == "sleep" | n_hours_covered >= 16,
         #type %in% c("sum", "mean")
         source == "sleep" | type %in% c("sum", "mean")) %>%
  select(userId, date, measurement, value) %>%
  unite("event", userId, date, sep = "_", remove = FALSE) %>%
  select(event, measurement, value) %>%
  distinct(event, measurement, .keep_all = TRUE) %>%
  pivot_wider(
    names_from = measurement,
    values_from = value,
    values_fill = NA
  ) %>%
  column_to_rownames("event")

presence_mat <- !is.na(df)
cooc_counts <- t(presence_mat) %*% presence_mat
cooc_perc <- cooc_counts / nrow(presence_mat) * 100

as_tibble(cooc_perc, rownames = "measurement_1") %>%
  pivot_longer(
    cols = -measurement_1,
    names_to = "measurement_2",
    values_to = "cooccurrence_perc") %>%
  mutate(
    measurement_1 = factor(measurement_1, levels = colnames(df)),
    measurement_2 = factor(measurement_2, levels = colnames(df))) %>%
  ggplot(aes(x = measurement_1, y = measurement_2, fill = cooccurrence_perc)) +
  geom_tile() +
  geom_text(aes(label = round(cooccurrence_perc, 1)), size = 3) +
  coord_fixed() +
  theme_minimal(base_size = 12) +
  labs(
    title = "Measurement co-occurrence matrix",
    subtitle = "Percentage of user-day events where both measurements are available",
    x = NULL, y = NULL, fill = "Co-occurrence (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid = element_blank()) +
  scale_fill_viridis_c(option = "viridis", limits = c(0, 100))

rm(df, presence_mat, cooc_counts, cooc_perc)
```


```{r}
info_daily <- triggerR$make_daily_wide_table(min_n_daily_obs_valid = 16,
                                             return_meta = T, with_sleep = F)
```

```{r}
summary_daily <- info_daily$data %>%
  as_tibble(rownames = "event") %>%
  left_join(as_tibble(info_daily$meta, rownames = "event"), by = "event") %>%
  left_join(heatwave, by = join_by(date, country))

sum(summary_daily$heatwave, na.rm = T) / sum(heatwave$heatwave, na.rm = T)

write_tsv(summary_daily, "ml_tpot2_subject_daily.csv")
```

## ONLY PHY

```{r, fig.width=12, fig.height=12}
df <- trigger_daily_with_sleep %>%
  filter(source %in% c("sleep", "smartwatchhigh", "smartwatchlow")) %>%
  filter(source != "gps", !is.na(value),
         !(userId == 61 & date == as.Date("2025-07-30")),
         #n_hours_covered >= 16,
         source == "sleep" | n_hours_covered >= 16,
         #type %in% c("sum", "mean")
         source == "sleep" | type %in% c("sum", "mean")) %>%
  select(userId, date, measurement, value) %>%
  unite("event", userId, date, sep = "_", remove = FALSE) %>%
  select(event, measurement, value) %>%
  distinct(event, measurement, .keep_all = TRUE) %>%
  pivot_wider(
    names_from = measurement,
    values_from = value,
    values_fill = NA
  ) %>%
  column_to_rownames("event")

presence_mat <- !is.na(df)
cooc_counts <- t(presence_mat) %*% presence_mat
cooc_perc <- cooc_counts / nrow(presence_mat) * 100

as_tibble(cooc_perc, rownames = "measurement_1") %>%
  pivot_longer(
    cols = -measurement_1,
    names_to = "measurement_2",
    values_to = "cooccurrence_perc") %>%
  mutate(
    measurement_1 = factor(measurement_1, levels = colnames(df)),
    measurement_2 = factor(measurement_2, levels = colnames(df))) %>%
  ggplot(aes(x = measurement_1, y = measurement_2, fill = cooccurrence_perc)) +
  geom_tile() +
  geom_text(aes(label = round(cooccurrence_perc, 1)), size = 3) +
  coord_fixed() +
  theme_minimal(base_size = 12) +
  labs(
    title = "Measurement co-occurrence matrix",
    subtitle = "Percentage of user-day events where both measurements are available",
    x = NULL, y = NULL, fill = "Co-occurrence (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid = element_blank()) +
  scale_fill_viridis_c(option = "viridis", limits = c(0, 100))

rm(df, presence_mat, cooc_counts, cooc_perc)
```

```{r}
info_daily_phy <- triggerR$make_daily_wide_table(min_n_daily_obs_valid = 16,
                               return_meta = T, with_sleep = T,
                               domain_filter = "physiological",
                               exclude_measurements = "breathrate") 
```

```{r}
summary_phy <- info_daily_phy$data %>%
  as_tibble(rownames = "event") %>%
  left_join(as_tibble(info_daily_phy$meta, rownames = "event"), by = "event") %>%
  left_join(heatwave, by = join_by(date, country)) %>%
  select(-event, -date, -country, -city) %>%
  filter(!is.na(heatwave))

sum(summary_phy$heatwave, na.rm = T) / sum(heatwave$heatwave, na.rm = T)
```


```{r}
write_tsv(summary_phy, "ml_tpot2_subject_daily_only_physiological.tsv")
```

















